### ISSUE TITLE
CaptureOutputToFd fails on arm64

### ISSUE THREAD

**Issue by sinzui** [spacemonkeygo/spacelog#5]
arm64 doesn't support syscall.Dup2, use syscall.Dup3 instead.

--- a/vendor/src/github.com/spacemonkeygo/spacelog/capture_other.go
+++ b/vendor/src/github.com/spacemonkeygo/spacelog/capture_other.go
@@ -23,11 +23,11 @@
 // CaptureOutputToFd redirects the current process' stdout and stderr file
 // descriptors to the given file descriptor, using the dup2 syscall.
 func CaptureOutputToFd(fd int) error {
-   err := syscall.Dup2(fd, syscall.Stdout)
-   err := syscall.Dup3(fd, syscall.Stdout, 0)
  if err != nil {
      return err
  }
-   err = syscall.Dup2(fd, syscall.Stderr)
-   err = syscall.Dup3(fd, syscall.Stderr, 0)
  if err != nil {
      return err
  }

**Comment by xdg** [comment]
Was this also resolved with #4?

**Comment by sinzui** [comment]
@xdg I agree with the fix. The linux-only solution does address the case I was seeing. I no longer have access to arm hardware to test this. I accept this bug is closed.
